jobs:
- job:
  displayName: 'vs2017-win2016'
  pool:
    vmImage: 'vs2017-win2016'

  steps:
  - powershell: |
      Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
      Write-Host "##vso[task.setvariable variable=CONDAPS1]$env:CONDA\Scripts\activate.ps1"
    displayName: Add conda to PATH

  - script: |
      conda create --yes --quiet --name chihiro
    displayName: Create Anaconda environment

  - script: |
      call activate chihiro
      conda install --yes --quiet --name chihiro openssl
    displayName: Install Anaconda packages

  # -I"${CONDA_PREFIX}"/include

  - powershell: |
      Write-Host "Agent name $Env:AGENT_NAME."
      Write-Host "Path variable is $Env:Path."
      ls $env:CONDA\shell\condabin\conda-hook.ps1 | Out-String | Write-Host
      Write-Host "boop"
      gci env:* | sort-object name | Out-String | Write-Host
    displayName: print PATH1

  # - powershell: |
  #     . $env:CONDAPS1 chihiro
  #     Write-Host "Agent name $Env:AGENT_NAME."
  #     Write-Host "Path variable is $Env:Path."
  #     gci env:* | sort-object name | Out-String | Write-Host
  #   displayName: print PATH2

